apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hives.hive.example.com
spec:
  group: hive.example.com
  names:
    kind: Hive
    listKind: HiveList
    plural: hives
    singular: hive
  scope: Namespaced
  version: v1alpha1
