apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-deployment
  labels:
    app: hive-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-operator
  template:
    metadata:
      labels:
        app: hive-operator
    spec:
      containers:
      - name: hive-operator
        image: quay.io/dgoodwin/hive:latest
        ports:
        - containerPort: 80